import type { Component } from 'vue'
import FormTable, {
  FormTable as NamedFormTable,
  type ColumnConfig,
  type FormTableExpose,
  type FormTableFieldHintFormatter,
  type FormTableFormItemProps,
  type FormTableFormProps,
  type FormTableHintOptions,
  type FormTableProps,
  type FormTableTableProps
} from '../index'
import { CustomInput, rows } from './public-api.fixtures'
import { columns } from './public-api.columns.typecheck'
import { typedColumns } from './public-api.component.typecheck'

interface PurchaseRow {
  name: string
  amount: number
  profile?: {
    city: string
  }
  items?: Array<{
    name: string
  }>
}

const props: FormTableProps = {
  tableData: rows,
  columns,
  rowKey: 'id',
  formProps: { size: 'small' },
  tableProps: { border: true },
  hintOptions: {
    mode: 'tooltip',
    targets: 'all',
    tooltipProps: { placement: 'top', openDelay: 200 }
  }
}
const formProps: FormTableFormProps = { size: 'small', disabled: false }
const tableProps: FormTableTableProps = { border: true, maxHeight: 480 }
const formItemProps: FormTableFormItemProps = {
  label: '姓名',
  rules: [{ required: true }]
}
const managedTableDataProps: FormTableTableProps = {
  // @ts-expect-error data is managed by the top-level tableData prop.
  data: rows
}
const managedTableRowKeyProps: FormTableTableProps = {
  // @ts-expect-error rowKey is managed by the top-level rowKey prop.
  rowKey: 'id'
}
const managedFormModelProps: FormTableFormProps = {
  // @ts-expect-error model is fixed to the internal { tableData } object.
  model: { tableData: rows }
}
const managedFormItemProp: FormTableFormItemProps = {
  // @ts-expect-error prop is generated from the row index and fieldKey.
  prop: 'tableData.0.name'
}
void formProps
void tableProps
void formItemProps
void managedTableDataProps
void managedTableRowKeyProps
void managedFormModelProps
void managedFormItemProp
const functionRowKeyProps: FormTableProps<PurchaseRow> = {
  tableData: [{ name: '采购单', amount: 10 }],
  columns: typedColumns,
  rowKey: row => row.name
}
const legacyRowKeyProps: FormTableProps = {
  tableData: rows,
  columns,
  tableProps: {
    // @ts-expect-error rowKey is a top-level FormTable prop.
    rowKey: 'id'
  }
}
const managedNestedProps: FormTableProps = {
  tableData: rows,
  columns: [{
    label: '姓名',
    formItems: [{
      fieldKey: 'name',
      type: 'input',
      formItemProps: {
        // @ts-expect-error FormItem prop is always generated by FormTable.
        prop: 'name'
      }
    }]
  }],
  formProps: {
    // @ts-expect-error Form model is always generated by FormTable.
    model: { tableData: rows }
  },
  tableProps: {
    // @ts-expect-error Table data is provided by the top-level tableData prop.
    data: rows
  }
}
void managedNestedProps
const titleHintOptions: FormTableHintOptions = { mode: 'title' }
const tooltipHintOptions: FormTableHintOptions = {
  mode: 'tooltip',
  targets: 'header',
  tooltipProps: { placement: 'bottom' }
}
const typedFieldFormatter: FormTableFieldHintFormatter<PurchaseRow> = ({ value, row }) => (
  `${row.name}:${String(value)}`
)
const typedDefaultFieldHint: FormTableHintOptions<PurchaseRow>['field'] = typedFieldFormatter
const typedHintOptions: FormTableHintOptions<PurchaseRow> = {
  mode: 'tooltip',
  field: typedDefaultFieldHint
}
const defaultStringHintOptions: FormTableHintOptions<PurchaseRow> = { field: true }
const disabledGlobalHintOptions: FormTableHintOptions<PurchaseRow> = { field: false }
void defaultStringHintOptions
void disabledGlobalHintOptions
const legacyFieldHintOptions: FormTableHintOptions<PurchaseRow> = {
  // @ts-expect-error 旧 field.enabled/formatter 对象不再接受。
  field: { enabled: true, formatter: typedFieldFormatter }
}
void legacyFieldHintOptions
void typedHintOptions
const disabledHintOptions: FormTableHintOptions = { mode: false }
// @ts-expect-error 旧 props 入口不再接受。
const invalidTooltipProps: FormTableHintOptions = { mode: 'tooltip', props: {} }
const legacyHintModeProps: FormTableProps = {
  tableData: rows,
  columns,
  // @ts-expect-error hintMode 已由 hintOptions 替代。
  hintMode: 'tooltip'
}
const legacyHintTooltipProps: FormTableProps = {
  tableData: rows,
  columns,
  // @ts-expect-error hintTooltipProps 已收敛到 hintOptions.tooltipProps。
  hintTooltipProps: { placement: 'top' }
}
void titleHintOptions
void tooltipHintOptions
void disabledHintOptions
void invalidTooltipProps
void legacyHintModeProps
void legacyHintTooltipProps
const component: Component = FormTable
const named: Component = NamedFormTable

async function useExpose(expose: FormTableExpose) {
  await expose.validate()
  expose.clearValidate()
  const row = { id: 'default-row' }
  void expose.getFieldProp(row, 'name')
  await expose.validateField(row, 'name')
  expose.clearFieldValidate(row, 'name')
  await expose.focusField(row, 'name')
  await expose.scrollToFirstError()
  expose.updateRows([{ row, patch: { name: 'updated' } }])
  return expose.getTableRef()
}

const invalid: ColumnConfig[] = [{
  label: '错误配置',
  formItems: [{
      fieldKey: 'bad',
      // @ts-expect-error unknown type aliases are rejected.
      type: 'unknown'
    }]
}]

const invalidModes: ColumnConfig[] = [{
  label: '渲染模式约束',
  formItems: [// @ts-expect-error builtin modes resolve their own component target.
      { fieldKey: 'name', type: 'input', component: { is: CustomInput } },
      // @ts-expect-error component mode requires is or resolveComponent.
      { fieldKey: 'custom', type: 'component', component: { props: {} } },
      // @ts-expect-error builtin modes cannot dynamically replace their component target.
      { fieldKey: 'dynamic-input', type: 'input', component: { resolveComponent: () => CustomInput } },
      // @ts-expect-error slot must be a string name.
      { fieldKey: 'actions', type: 'slot', component: { slot: CustomInput } },
      // @ts-expect-error slot mode does not accept a component target.
      { fieldKey: 'legacy-slot-target', type: 'slot', component: { is: 'actions' } },
      // @ts-expect-error slot names remain static and do not use component resolution.
      { fieldKey: 'dynamic-slot', type: 'slot', component: { slot: 'actions', resolveComponent: () => CustomInput } },
      // @ts-expect-error component mode does not accept a slot target.
      { fieldKey: 'component-slot', type: 'component', component: { slot: 'actions' } },
      // @ts-expect-error renderer was replaced by is.
      { fieldKey: 'legacy-renderer', type: 'component', component: { renderer: CustomInput } },
      // @ts-expect-error resolveRenderer was replaced by resolveComponent.
      { fieldKey: 'legacy-resolver', type: 'component', component: { resolveRenderer: () => CustomInput } },
      // @ts-expect-error component resolution is synchronous and does not accept Promise results.
      { fieldKey: 'async-is', type: 'component', component: { resolveComponent: async () => CustomInput } }]
}]

const renamedColumn: ColumnConfig = {
  label: '新字段名',
  // @ts-expect-error ColumnConfig uses label; legacy name is not accepted.
  name: '旧字段名',
  formItems: []
}

const renamedItem: ColumnConfig = {
  label: '字段路径',
  formItems: [// @ts-expect-error key is only the render identity; fieldKey remains required.
      { key: 'name', type: 'input' }]
}

const keyedItem: ColumnConfig = {
  label: '稳定字段身份',
  formItems: [{ key: 'primary-name', fieldKey: 'name', type: 'input' }]
}

const itemMetaVariants: ColumnConfig[] = [{
  label: '静态字段元数据',
  formItems: [
    { fieldKey: 'name', type: 'input', meta: { role: 'builtin' } },
    {
      fieldKey: 'custom',
      type: 'component',
      meta: { role: 'component' },
      visible: ({ itemConfig }) => itemConfig.meta?.role === 'component',
      component: {
        is: CustomInput,
        props: ({ itemConfig }) => ({ role: itemConfig.meta?.role }),
        listeners: {
          change({ itemConfig }) {
            void itemConfig.meta?.role
          }
        }
      }
    },
    {
      fieldKey: 'actions',
      type: 'slot',
      meta: { role: 'slot', permission: 'row:update' },
      component: { slot: 'actions' }
    }
  ]
}]

const invalidDynamicItemMeta: ColumnConfig = {
  label: '动态字段元数据',
  formItems: [{
    fieldKey: 'name',
    type: 'input',
    // @ts-expect-error meta is static metadata and does not accept a resolver.
    meta: () => ({ role: 'dynamic' })
  }]
}

const legacySlotString: ColumnConfig = {
  label: '旧 slot 写法',
  formItems: [// @ts-expect-error standalone slot field was replaced by type: 'slot' + component.slot.
      { fieldKey: 'actions', slot: 'actions' }]
}

const legacyComponentIs: ColumnConfig = {
  label: '旧组件写法',
  formItems: [// @ts-expect-error component mode requires type: 'component' + component.is.
      { fieldKey: 'custom', component: { is: CustomInput } }]
}

void [
  props,
  functionRowKeyProps,
  legacyRowKeyProps,
  component,
  named,
  useExpose,
  invalid,
  invalidModes,
  renamedColumn,
  renamedItem,
  keyedItem,
  itemMetaVariants,
  invalidDynamicItemMeta,
  legacySlotString,
  legacyComponentIs
]
